server:
  port: 8999
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        payload-in:
          destination: input-payload-topic
          contentType: application/json
        payload-out:
          destination: output-payload-topic
          contentType: application/json
